name: docker build
on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      tags:
        type: string
        required: true
      DOCKER_USER:
        type: string
        default: ${{ vars.DOCKER_USER }}
    secrets:
      DOCKER_TOKEN:
        required: true
    outputs:
      image_url:
        value: ${{ jobs.docker-build.outputs.image_url }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs: 
      image_url: ${{ steps.set-output.outputs.image_url }}
    steps:
    # 1. Fetch your code from the repository
    - name: checkout code
      uses: actions/checkout@v5
    
    # 2. Create and boot the BuildKit builder instance
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. Authenticate to your container registry - dockerhub
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ inputs.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # 4. Build and push docker image
    - name: build docker image
      id: docker-push
      uses: docker/build-push-action@v5
      with:
        context: .
       # Pushes to docker hub
        push: true
        tags: |
          ${{ inputs.tags }}
    
    # 5. Set image URL
    - name: Set image URL output
      id: set-output
      run: |
        echo "image_url=${{ vars.DOCKER_USER }}/${{ inputs.image_name }}:latest" >> $GITHUB_OUTPUT
    
    # 6. Scan image vulnarability
    - name: Trivy scan
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        image-ref: ${{ steps.set-output.outputs.image_url }}
        format: 'json'
        exit-code: '1'                # fails for mentioned severity
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'     # evaluates critical and high vulnarability
        output: 'trivy-report.json'
    
    # 7. upload the trivy scan report
    - name: upload the trivy report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-scan-report
        path: trivy-report.json
        retention-days: 30